# File: templates/scancentral-dast-scan.yml

# defaults for any parameters that aren't specified
parameters: 
- name: 'pool'
  type: object
  default: {}
- name: workingDirectory
  default: ''
- name: projectFile
  default: '*.csproj'
- name: dotnetVersion
  default: '6.x'
- name: buildConfiguration
  default: 'Debug'
- name: vsVersion
  default: '2022'
- name: vsEdition
  default: 'Community'
- name: jdkVersion
  default: '17'
- name: jdkArch
  default: 'x64'
- name: notificationEmail
  default: 'somebody@somewhere.com'
- name: sscUrl
- name: sscCiToken
- name: sscAppName
- name: sscAppVerName
- name: sscParentAppVerName
  default: 'main'
- name: sscIssueTemplate
  default: 'Prioritized-HighRisk-Project-Template'

jobs:
- job: ScanCentralDynamicScan
  pool: ${{ parameters.pool }}
  steps:
  - task: UseDotNet@2
    inputs:
      version: ${{ parameters.dotnetVersion }}
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: ${{ parameters.jdkVersion }}
      jdkArchitectureOption: ${{ parameters.jdkArch }}
      jdkSourceOption: PreInstalled
  - task: FcliInstaller@0
    inputs:
      version: 'latest'
  - task: PowerShell@2
    displayName: 'SSC Check AppVersion'
    inputs:
      targetType: 'inline'
      script: |
        $App="${env:SSC_APP_NAME}"
        $Rel="${env:SSC_APPVER_NAME}"
        if (${env:FORTIFY_APP_NAME_OVERRIDE}) {
          Write-Host "##[debug]Overriding FORTIFY_APP_NAME to ${env:FORTIFY_APP_NAME_OVERRIDE}"
          Write-Host "##vso[task.setvariable variable=FORTIFY_APP_NAME]${env:FORTIFY_APP_NAME_OVERRIDE}"
          $App="${env:FORTIFY_APP_NAME_OVERRIDE}"
        } else {
          Write-Host "##[command]Using FORTIFY_APP_NAME ${App}"
        }
        if (${env:FORTIFY_RELEASE_NAME_OVERRIDE}) {
          Write-Host "##[debug]Overriding FORTIFY_RELEASE_NAME to ${env:FORTIFY_RELEASE_NAME_OVERRIDE}"
          Write-Host "##vso[task.setvariable variable=FORTIFY_RELEASE_NAME]${env:FORTIFY_RELEASE_NAME_OVERRIDE}"
          $Rel=${env:FORTIFY_RELEASE_NAME_OVERRIDE}
        } else {
          Write-Host "##[debug]Using FORTIFY_RELEASE_NAME ${Rel}"
        }
        Write-Host "##[command]fcli sc-dast session login --ssc-url ""${env:SSC_URL}"" --ssc-ci-token ""${env:SSC_CI_TOKEN}"" --session azure-pipelines"
        fcli sc-dast session login --ssc-url "${env:SSC_URL}" --ssc-ci-token "${env:SSC_CI_TOKEN}" --session azure-pipelines
        Write-Host "##[command]fcli ssc appversion list -q ""application.name=='${App}'"""
        fcli ssc appversion list -q "application.name=='${App}'" --session azure-pipelines
        Write-Host "##[command]fcli ssc appversion create ""${App}:${Rel}"" --description ""Created automatically from Azure DevOps"" --auto-required-attrs --skip-if-exists --issue-template ${env:SSC_ISSUE_TEMPLATE} -o expr=""{releaseId}"" --session azure-pipelines"
        $AppVerId=(fcli ssc appversion create "${App}:${Rel}" --description "Created automatically from Azure DevOps" --auto-required-attrs --skip-if-exists --issue-template ${env:SSC_ISSUE_TEMPLATE} -o expr="{id}" --session azure-pipelines)
        Write-Host "##[debug]Setting sscAppVerId to $AppVerId"
        Write-Host "##vso[task.setvariable variable=sscAppVerId]$AppVerId"
      showWarnings: true
    env:
      SSC_URL: ${{ parameters.sscUrl }}
      SSC_CI_TOKEN: ${{ parameters.sscCiToken }}
      SSC_APP_NAME: ${{ parameters.sscAppName }}
      SSC_APPVER_NAME: ${{ parameters.sscAppVerName }}
      SSC_PARENT_APPVER_NAME: ${{ parameters.sscParentAppVerName }}
      SSC_ISSUE_TEMPLATE: ${{ parameters.sscIssueTemplate }}
  - task: PowerShell@2
    displayName: 'Fortify ScanCentral DAST scan'
    inputs:
      targetType: 'inline'
      script: |
        Write-Host "##[debug]Not yet implemented"
      workingDirectory: ${{ parameters.workingDirectory }}
    env:
      SSC_URL: ${{ parameters.sscUrl }}
      SSC_APPVER_ID: $(sscAppVerId)
      SSC_CI_TOKEN: ${{ parameters.sscCiToken }}
      NOTIFY_EMAIL: ${{ parameters.notificationEmail }}
  - task: PowerShell@2
    displayName: 'SSC Logout'
    inputs:
      targetType: 'inline'
      script: |
        Write-Host "##[command]fcli sc-dast session logout --no-revoke-token --session azure-pipelines"
        fcli sc-dast session logout --no-revoke-token --session azure-pipelines
